{
    'name': 'Custom Invoice Extension',
    'version': '1.0',
    'depends': ['account'],
    'author': 'Mohannad Waheed',
    'sequence': '1',
    'images': ['static/description/banner.png'],
    'website': 'https://www.linkedin.com/in/mohannad-waheed-3a3b98200/',
    'license': 'LGPL-3',
    'category': 'Accounting',
    'description': 'Adds payment type and method to invoices',
    'data': ['views/account_move_views.xml'],
    'application': True,
    'installable': True,
}
