{
    'name': 'Auto payment Invoice Extension',
    'version': '1.0',
    'depends': ['account'],
    'author': 'Mohannad Waheed',
    'summary': 'Extends the invoice model to include payment type and method',
    'sequence': '1',
    'images': ['static/description/banner.png'   , 
               'static/description/banner2.png'],
    'website': 'https://www.linkedin.com/in/mohannadwaheed/',
    'license': 'LGPL-3',
    'category': 'Accounting',
    'description': 'Adds payment type and method to invoices',
    'data': ['views/account_move_views.xml'],
    'application': True,
    'installable': True,
}
